//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.XApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Tunes.XApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ActionSheetButton_Cancel {
            get {
                return ResourceManager.GetString("ActionSheetButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ActionSheetButton_Delete {
            get {
                return ResourceManager.GetString("ActionSheetButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play all.
        /// </summary>
        internal static string AlbumsDetailPage_Button_PlayAll_Text {
            get {
                return ResourceManager.GetString("AlbumsDetailPage_Button_PlayAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle all.
        /// </summary>
        internal static string AlbumsDetailPage_Button_PlayRandomized_Text {
            get {
                return ResourceManager.GetString("AlbumsDetailPage_Button_PlayRandomized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string AlbumsPage_Title {
            get {
                return ResourceManager.GetString("AlbumsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Dialog_Result_Ok {
            get {
                return ResourceManager.GetString("Dialog_Result_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string HomePage_AlbumsCarousel_SectionHeader_Button_Text {
            get {
                return ResourceManager.GetString("HomePage_AlbumsCarousel_SectionHeader_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats New.
        /// </summary>
        internal static string HomePage_FeatAlbums_SectionHeader_Button_Text {
            get {
                return ResourceManager.GetString("HomePage_FeatAlbums_SectionHeader_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have {0} songs and if you have enough time we play them all..
        /// </summary>
        internal static string HomePage_RandomPlayerButton_Button_Text {
            get {
                return ResourceManager.GetString("HomePage_RandomPlayerButton_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_Button_Text_Login {
            get {
                return ResourceManager.GetString("LoginPage_Button_Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string LoginPage_Entry_Placeholder_EnterPassword {
            get {
                return ResourceManager.GetString("LoginPage_Entry_Placeholder_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string LoginPage_Entry_Placeholder_EnterUserName {
            get {
                return ResourceManager.GetString("LoginPage_Entry_Placeholder_EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system could not log you on. Ensure that you entered your details correctly and try again..
        /// </summary>
        internal static string LoginPageViewModel_LoginException {
            get {
                return ResourceManager.GetString("LoginPageViewModel_LoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete your account for this BSETunes?.
        /// </summary>
        internal static string LoginSettingsPage_ActionSheet_Title {
            get {
                return ResourceManager.GetString("LoginSettingsPage_ActionSheet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string LoginSettingsPage_ButtonDelete_Text {
            get {
                return ResourceManager.GetString("LoginSettingsPage_ButtonDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account at BSEtunes.
        /// </summary>
        internal static string LoginSettingsPage_SectionAccount_Description_Text {
            get {
                return ResourceManager.GetString("LoginSettingsPage_SectionAccount_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string LoginSettingsPage_SectionAccount_Title {
            get {
                return ResourceManager.GetString("LoginSettingsPage_SectionAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string LoginSettingsPage_Title {
            get {
                return ResourceManager.GetString("LoginSettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string PlaylistsPage_Title {
            get {
                return ResourceManager.GetString("PlaylistsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the address of this BSETunes?.
        /// </summary>
        internal static string ServiceEndpointSettingsPage_ActionSheet_Title {
            get {
                return ResourceManager.GetString("ServiceEndpointSettingsPage_ActionSheet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Address.
        /// </summary>
        internal static string ServiceEndpointSettingsPage_ButtonDelete_Text {
            get {
                return ResourceManager.GetString("ServiceEndpointSettingsPage_ButtonDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web address of your BSEtunes.
        /// </summary>
        internal static string ServiceEndpointSettingsPage_SectionWebserver_Description_Text {
            get {
                return ResourceManager.GetString("ServiceEndpointSettingsPage_SectionWebserver_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string ServiceEndpointSettingsPage_SectionWebserver_Title {
            get {
                return ResourceManager.GetString("ServiceEndpointSettingsPage_SectionWebserver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webserver.
        /// </summary>
        internal static string ServiceEndpointSettingsPage_Title {
            get {
                return ResourceManager.GetString("ServiceEndpointSettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account at BSEtunes.
        /// </summary>
        internal static string SettingsPage_SectionAccount_Description_Text {
            get {
                return ResourceManager.GetString("SettingsPage_SectionAccount_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string SettingsPage_SectionAccount_Title {
            get {
                return ResourceManager.GetString("SettingsPage_SectionAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web address of your BSEtunes.
        /// </summary>
        internal static string SettingsPage_SectionWebserver_Description_Text {
            get {
                return ResourceManager.GetString("SettingsPage_SectionWebserver_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webserver.
        /// </summary>
        internal static string SettingsPage_SectionWebserver_Title {
            get {
                return ResourceManager.GetString("SettingsPage_SectionWebserver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
    }
}
